//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DSI.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ciudad
    {
        public byte id { get; set; }
        public string NCiudad { get; set; }
        public Nullable<byte> id_pais { get; set; }
    }
}
