//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DSI.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class contacto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public contacto()
        {
            this.Documentos = new HashSet<Documentos>();
        }
    
        public int id { get; set; }
        public string Nombre { get; set; }
        public string Razón_Social { get; set; }
        public string Telefono { get; set; }
        public string Direccion { get; set; }
        public string Correo { get; set; }
        public string Descripcion { get; set; }
        public string Sector_Actividad { get; set; }
        public Nullable<byte> id_sector { get; set; }
        public Nullable<byte> id_ubicacion { get; set; }
        public Nullable<bool> id_categoria { get; set; }
        public Nullable<bool> id_estado { get; set; }
        public string ruta_carpeta { get; set; }
    
        public virtual Categoria Categoria { get; set; }
        public virtual Ciudad Ciudad { get; set; }
        public virtual Tipo_Estado Tipo_Estado { get; set; }
        public virtual sector sector { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Documentos> Documentos { get; set; }
    }
}
