//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DSI.Datos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class DSIEntities1 : DbContext
    {
        public DSIEntities1()
            : base("name=DSIEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Categoria> Categoria { get; set; }
        public virtual DbSet<Ciudad> Ciudad { get; set; }
        public virtual DbSet<Pais> Pais { get; set; }
        public virtual DbSet<Roles> Roles { get; set; }
        public virtual DbSet<sector> sector { get; set; }
        public virtual DbSet<Tipo_Estado> Tipo_Estado { get; set; }
        public virtual DbSet<Usuarios> Usuarios { get; set; }
        public virtual DbSet<contacto> contacto { get; set; }
        public virtual DbSet<Documentos> Documentos { get; set; }
    
        public virtual int sp_alterdiagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_alterdiagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual ObjectResult<sp_consultaContacto_Result> sp_consultaContacto(Nullable<bool> id_categoria)
        {
            var id_categoriaParameter = id_categoria.HasValue ?
                new ObjectParameter("id_categoria", id_categoria) :
                new ObjectParameter("id_categoria", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_consultaContacto_Result>("sp_consultaContacto", id_categoriaParameter);
        }
    
        public virtual ObjectResult<sp_consultaContacto2_Result> sp_consultaContacto2(Nullable<bool> id_categoria)
        {
            var id_categoriaParameter = id_categoria.HasValue ?
                new ObjectParameter("id_categoria", id_categoria) :
                new ObjectParameter("id_categoria", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_consultaContacto2_Result>("sp_consultaContacto2", id_categoriaParameter);
        }
    
        public virtual ObjectResult<sp_consultaContactoFiltro_Result> sp_consultaContactoFiltro(string nombre, string r_social, string sector, string ciudad, string pais, string id_categoria)
        {
            var nombreParameter = nombre != null ?
                new ObjectParameter("nombre", nombre) :
                new ObjectParameter("nombre", typeof(string));
    
            var r_socialParameter = r_social != null ?
                new ObjectParameter("r_social", r_social) :
                new ObjectParameter("r_social", typeof(string));
    
            var sectorParameter = sector != null ?
                new ObjectParameter("sector", sector) :
                new ObjectParameter("sector", typeof(string));
    
            var ciudadParameter = ciudad != null ?
                new ObjectParameter("ciudad", ciudad) :
                new ObjectParameter("ciudad", typeof(string));
    
            var paisParameter = pais != null ?
                new ObjectParameter("pais", pais) :
                new ObjectParameter("pais", typeof(string));
    
            var id_categoriaParameter = id_categoria != null ?
                new ObjectParameter("id_categoria", id_categoria) :
                new ObjectParameter("id_categoria", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_consultaContactoFiltro_Result>("sp_consultaContactoFiltro", nombreParameter, r_socialParameter, sectorParameter, ciudadParameter, paisParameter, id_categoriaParameter);
        }
    
        public virtual int sp_creatediagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_creatediagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_dropdiagram(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_dropdiagram", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_filtroFiveOne_Result> sp_filtroFiveOne(string nombre, Nullable<byte> sector, Nullable<byte> ciudad, Nullable<byte> pais, Nullable<bool> id_categoria)
        {
            var nombreParameter = nombre != null ?
                new ObjectParameter("nombre", nombre) :
                new ObjectParameter("nombre", typeof(string));
    
            var sectorParameter = sector.HasValue ?
                new ObjectParameter("sector", sector) :
                new ObjectParameter("sector", typeof(byte));
    
            var ciudadParameter = ciudad.HasValue ?
                new ObjectParameter("ciudad", ciudad) :
                new ObjectParameter("ciudad", typeof(byte));
    
            var paisParameter = pais.HasValue ?
                new ObjectParameter("pais", pais) :
                new ObjectParameter("pais", typeof(byte));
    
            var id_categoriaParameter = id_categoria.HasValue ?
                new ObjectParameter("id_categoria", id_categoria) :
                new ObjectParameter("id_categoria", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_filtroFiveOne_Result>("sp_filtroFiveOne", nombreParameter, sectorParameter, ciudadParameter, paisParameter, id_categoriaParameter);
        }
    
        public virtual ObjectResult<sp_filtroFiveTwo_Result> sp_filtroFiveTwo(string r_social, Nullable<byte> ciudad, Nullable<byte> pais, Nullable<bool> id_categoria)
        {
            var r_socialParameter = r_social != null ?
                new ObjectParameter("r_social", r_social) :
                new ObjectParameter("r_social", typeof(string));
    
            var ciudadParameter = ciudad.HasValue ?
                new ObjectParameter("ciudad", ciudad) :
                new ObjectParameter("ciudad", typeof(byte));
    
            var paisParameter = pais.HasValue ?
                new ObjectParameter("pais", pais) :
                new ObjectParameter("pais", typeof(byte));
    
            var id_categoriaParameter = id_categoria.HasValue ?
                new ObjectParameter("id_categoria", id_categoria) :
                new ObjectParameter("id_categoria", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_filtroFiveTwo_Result>("sp_filtroFiveTwo", r_socialParameter, ciudadParameter, paisParameter, id_categoriaParameter);
        }
    
        public virtual ObjectResult<sp_filtroFour_Result> sp_filtroFour(string pais, Nullable<bool> id_categoria)
        {
            var paisParameter = pais != null ?
                new ObjectParameter("pais", pais) :
                new ObjectParameter("pais", typeof(string));
    
            var id_categoriaParameter = id_categoria.HasValue ?
                new ObjectParameter("id_categoria", id_categoria) :
                new ObjectParameter("id_categoria", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_filtroFour_Result>("sp_filtroFour", paisParameter, id_categoriaParameter);
        }
    
        public virtual ObjectResult<sp_filtroFourFive_Result> sp_filtroFourFive(string ciudad, string pais, Nullable<bool> id_categoria)
        {
            var ciudadParameter = ciudad != null ?
                new ObjectParameter("ciudad", ciudad) :
                new ObjectParameter("ciudad", typeof(string));
    
            var paisParameter = pais != null ?
                new ObjectParameter("pais", pais) :
                new ObjectParameter("pais", typeof(string));
    
            var id_categoriaParameter = id_categoria.HasValue ?
                new ObjectParameter("id_categoria", id_categoria) :
                new ObjectParameter("id_categoria", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_filtroFourFive_Result>("sp_filtroFourFive", ciudadParameter, paisParameter, id_categoriaParameter);
        }
    
        public virtual ObjectResult<sp_filtroFourOne_Result> sp_filtroFourOne(string nombre, Nullable<byte> sector, Nullable<byte> pais, Nullable<bool> id_categoria)
        {
            var nombreParameter = nombre != null ?
                new ObjectParameter("nombre", nombre) :
                new ObjectParameter("nombre", typeof(string));
    
            var sectorParameter = sector.HasValue ?
                new ObjectParameter("sector", sector) :
                new ObjectParameter("sector", typeof(byte));
    
            var paisParameter = pais.HasValue ?
                new ObjectParameter("pais", pais) :
                new ObjectParameter("pais", typeof(byte));
    
            var id_categoriaParameter = id_categoria.HasValue ?
                new ObjectParameter("id_categoria", id_categoria) :
                new ObjectParameter("id_categoria", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_filtroFourOne_Result>("sp_filtroFourOne", nombreParameter, sectorParameter, paisParameter, id_categoriaParameter);
        }
    
        public virtual ObjectResult<sp_filtroFourTwo_Result> sp_filtroFourTwo(string r_social, Nullable<byte> pais, Nullable<bool> id_categoria)
        {
            var r_socialParameter = r_social != null ?
                new ObjectParameter("r_social", r_social) :
                new ObjectParameter("r_social", typeof(string));
    
            var paisParameter = pais.HasValue ?
                new ObjectParameter("pais", pais) :
                new ObjectParameter("pais", typeof(byte));
    
            var id_categoriaParameter = id_categoria.HasValue ?
                new ObjectParameter("id_categoria", id_categoria) :
                new ObjectParameter("id_categoria", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_filtroFourTwo_Result>("sp_filtroFourTwo", r_socialParameter, paisParameter, id_categoriaParameter);
        }
    
        public virtual ObjectResult<sp_filtroOneFive_Result> sp_filtroOneFive(string nombre, string r_social, Nullable<byte> sector, Nullable<byte> ciudad, Nullable<byte> pais, Nullable<bool> id_categoria)
        {
            var nombreParameter = nombre != null ?
                new ObjectParameter("nombre", nombre) :
                new ObjectParameter("nombre", typeof(string));
    
            var r_socialParameter = r_social != null ?
                new ObjectParameter("r_social", r_social) :
                new ObjectParameter("r_social", typeof(string));
    
            var sectorParameter = sector.HasValue ?
                new ObjectParameter("sector", sector) :
                new ObjectParameter("sector", typeof(byte));
    
            var ciudadParameter = ciudad.HasValue ?
                new ObjectParameter("ciudad", ciudad) :
                new ObjectParameter("ciudad", typeof(byte));
    
            var paisParameter = pais.HasValue ?
                new ObjectParameter("pais", pais) :
                new ObjectParameter("pais", typeof(byte));
    
            var id_categoriaParameter = id_categoria.HasValue ?
                new ObjectParameter("id_categoria", id_categoria) :
                new ObjectParameter("id_categoria", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_filtroOneFive_Result>("sp_filtroOneFive", nombreParameter, r_socialParameter, sectorParameter, ciudadParameter, paisParameter, id_categoriaParameter);
        }
    
        public virtual ObjectResult<sp_filtroOneFour_Result> sp_filtroOneFour(string nombre, string r_social, string sector, string pais, Nullable<bool> id_categoria)
        {
            var nombreParameter = nombre != null ?
                new ObjectParameter("nombre", nombre) :
                new ObjectParameter("nombre", typeof(string));
    
            var r_socialParameter = r_social != null ?
                new ObjectParameter("r_social", r_social) :
                new ObjectParameter("r_social", typeof(string));
    
            var sectorParameter = sector != null ?
                new ObjectParameter("sector", sector) :
                new ObjectParameter("sector", typeof(string));
    
            var paisParameter = pais != null ?
                new ObjectParameter("pais", pais) :
                new ObjectParameter("pais", typeof(string));
    
            var id_categoriaParameter = id_categoria.HasValue ?
                new ObjectParameter("id_categoria", id_categoria) :
                new ObjectParameter("id_categoria", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_filtroOneFour_Result>("sp_filtroOneFour", nombreParameter, r_socialParameter, sectorParameter, paisParameter, id_categoriaParameter);
        }
    
        public virtual ObjectResult<sp_filtroOneTFive_Result> sp_filtroOneTFive(string nombre, string r_social, Nullable<byte> ciudad, Nullable<byte> pais, Nullable<bool> id_categoria)
        {
            var nombreParameter = nombre != null ?
                new ObjectParameter("nombre", nombre) :
                new ObjectParameter("nombre", typeof(string));
    
            var r_socialParameter = r_social != null ?
                new ObjectParameter("r_social", r_social) :
                new ObjectParameter("r_social", typeof(string));
    
            var ciudadParameter = ciudad.HasValue ?
                new ObjectParameter("ciudad", ciudad) :
                new ObjectParameter("ciudad", typeof(byte));
    
            var paisParameter = pais.HasValue ?
                new ObjectParameter("pais", pais) :
                new ObjectParameter("pais", typeof(byte));
    
            var id_categoriaParameter = id_categoria.HasValue ?
                new ObjectParameter("id_categoria", id_categoria) :
                new ObjectParameter("id_categoria", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_filtroOneTFive_Result>("sp_filtroOneTFive", nombreParameter, r_socialParameter, ciudadParameter, paisParameter, id_categoriaParameter);
        }
    
        public virtual ObjectResult<sp_filtroOneTFour_Result> sp_filtroOneTFour(string nombre, string r_social, Nullable<byte> pais, Nullable<bool> id_categoria)
        {
            var nombreParameter = nombre != null ?
                new ObjectParameter("nombre", nombre) :
                new ObjectParameter("nombre", typeof(string));
    
            var r_socialParameter = r_social != null ?
                new ObjectParameter("r_social", r_social) :
                new ObjectParameter("r_social", typeof(string));
    
            var paisParameter = pais.HasValue ?
                new ObjectParameter("pais", pais) :
                new ObjectParameter("pais", typeof(byte));
    
            var id_categoriaParameter = id_categoria.HasValue ?
                new ObjectParameter("id_categoria", id_categoria) :
                new ObjectParameter("id_categoria", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_filtroOneTFour_Result>("sp_filtroOneTFour", nombreParameter, r_socialParameter, paisParameter, id_categoriaParameter);
        }
    
        public virtual ObjectResult<sp_filtroOneThree_Result> sp_filtroOneThree(string nombre, string r_social, string sector, Nullable<bool> id_categoria)
        {
            var nombreParameter = nombre != null ?
                new ObjectParameter("nombre", nombre) :
                new ObjectParameter("nombre", typeof(string));
    
            var r_socialParameter = r_social != null ?
                new ObjectParameter("r_social", r_social) :
                new ObjectParameter("r_social", typeof(string));
    
            var sectorParameter = sector != null ?
                new ObjectParameter("sector", sector) :
                new ObjectParameter("sector", typeof(string));
    
            var id_categoriaParameter = id_categoria.HasValue ?
                new ObjectParameter("id_categoria", id_categoria) :
                new ObjectParameter("id_categoria", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_filtroOneThree_Result>("sp_filtroOneThree", nombreParameter, r_socialParameter, sectorParameter, id_categoriaParameter);
        }
    
        public virtual ObjectResult<sp_filtroOneTwo_Result> sp_filtroOneTwo(string nombre, string r_social, Nullable<bool> id_categoria)
        {
            var nombreParameter = nombre != null ?
                new ObjectParameter("nombre", nombre) :
                new ObjectParameter("nombre", typeof(string));
    
            var r_socialParameter = r_social != null ?
                new ObjectParameter("r_social", r_social) :
                new ObjectParameter("r_social", typeof(string));
    
            var id_categoriaParameter = id_categoria.HasValue ?
                new ObjectParameter("id_categoria", id_categoria) :
                new ObjectParameter("id_categoria", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_filtroOneTwo_Result>("sp_filtroOneTwo", nombreParameter, r_socialParameter, id_categoriaParameter);
        }
    
        public virtual ObjectResult<sp_filtroThree_Result> sp_filtroThree(Nullable<byte> sector, Nullable<bool> id_categoria)
        {
            var sectorParameter = sector.HasValue ?
                new ObjectParameter("sector", sector) :
                new ObjectParameter("sector", typeof(byte));
    
            var id_categoriaParameter = id_categoria.HasValue ?
                new ObjectParameter("id_categoria", id_categoria) :
                new ObjectParameter("id_categoria", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_filtroThree_Result>("sp_filtroThree", sectorParameter, id_categoriaParameter);
        }
    
        public virtual ObjectResult<sp_filtroThreeFive_Result> sp_filtroThreeFive(string sector, string ciudad, string pais, Nullable<bool> id_categoria)
        {
            var sectorParameter = sector != null ?
                new ObjectParameter("sector", sector) :
                new ObjectParameter("sector", typeof(string));
    
            var ciudadParameter = ciudad != null ?
                new ObjectParameter("ciudad", ciudad) :
                new ObjectParameter("ciudad", typeof(string));
    
            var paisParameter = pais != null ?
                new ObjectParameter("pais", pais) :
                new ObjectParameter("pais", typeof(string));
    
            var id_categoriaParameter = id_categoria.HasValue ?
                new ObjectParameter("id_categoria", id_categoria) :
                new ObjectParameter("id_categoria", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_filtroThreeFive_Result>("sp_filtroThreeFive", sectorParameter, ciudadParameter, paisParameter, id_categoriaParameter);
        }
    
        public virtual ObjectResult<sp_filtroThreeFour_Result> sp_filtroThreeFour(string sector, string pais, Nullable<bool> id_categoria)
        {
            var sectorParameter = sector != null ?
                new ObjectParameter("sector", sector) :
                new ObjectParameter("sector", typeof(string));
    
            var paisParameter = pais != null ?
                new ObjectParameter("pais", pais) :
                new ObjectParameter("pais", typeof(string));
    
            var id_categoriaParameter = id_categoria.HasValue ?
                new ObjectParameter("id_categoria", id_categoria) :
                new ObjectParameter("id_categoria", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_filtroThreeFour_Result>("sp_filtroThreeFour", sectorParameter, paisParameter, id_categoriaParameter);
        }
    
        public virtual ObjectResult<sp_filtroThreeOne_Result> sp_filtroThreeOne(string nombre, Nullable<byte> sector, Nullable<bool> id_categoria)
        {
            var nombreParameter = nombre != null ?
                new ObjectParameter("nombre", nombre) :
                new ObjectParameter("nombre", typeof(string));
    
            var sectorParameter = sector.HasValue ?
                new ObjectParameter("sector", sector) :
                new ObjectParameter("sector", typeof(byte));
    
            var id_categoriaParameter = id_categoria.HasValue ?
                new ObjectParameter("id_categoria", id_categoria) :
                new ObjectParameter("id_categoria", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_filtroThreeOne_Result>("sp_filtroThreeOne", nombreParameter, sectorParameter, id_categoriaParameter);
        }
    
        public virtual ObjectResult<sp_filtroTwo_Result> sp_filtroTwo(string r_social, Nullable<bool> id_categoria)
        {
            var r_socialParameter = r_social != null ?
                new ObjectParameter("r_social", r_social) :
                new ObjectParameter("r_social", typeof(string));
    
            var id_categoriaParameter = id_categoria.HasValue ?
                new ObjectParameter("id_categoria", id_categoria) :
                new ObjectParameter("id_categoria", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_filtroTwo_Result>("sp_filtroTwo", r_socialParameter, id_categoriaParameter);
        }
    
        public virtual ObjectResult<sp_filtroTwoFive_Result> sp_filtroTwoFive(string r_social, Nullable<byte> sector, Nullable<byte> ciudad, Nullable<byte> pais, Nullable<bool> id_categoria)
        {
            var r_socialParameter = r_social != null ?
                new ObjectParameter("r_social", r_social) :
                new ObjectParameter("r_social", typeof(string));
    
            var sectorParameter = sector.HasValue ?
                new ObjectParameter("sector", sector) :
                new ObjectParameter("sector", typeof(byte));
    
            var ciudadParameter = ciudad.HasValue ?
                new ObjectParameter("ciudad", ciudad) :
                new ObjectParameter("ciudad", typeof(byte));
    
            var paisParameter = pais.HasValue ?
                new ObjectParameter("pais", pais) :
                new ObjectParameter("pais", typeof(byte));
    
            var id_categoriaParameter = id_categoria.HasValue ?
                new ObjectParameter("id_categoria", id_categoria) :
                new ObjectParameter("id_categoria", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_filtroTwoFive_Result>("sp_filtroTwoFive", r_socialParameter, sectorParameter, ciudadParameter, paisParameter, id_categoriaParameter);
        }
    
        public virtual ObjectResult<sp_filtroTwoFour_Result> sp_filtroTwoFour(string r_social, string sector, string pais, Nullable<bool> id_categoria)
        {
            var r_socialParameter = r_social != null ?
                new ObjectParameter("r_social", r_social) :
                new ObjectParameter("r_social", typeof(string));
    
            var sectorParameter = sector != null ?
                new ObjectParameter("sector", sector) :
                new ObjectParameter("sector", typeof(string));
    
            var paisParameter = pais != null ?
                new ObjectParameter("pais", pais) :
                new ObjectParameter("pais", typeof(string));
    
            var id_categoriaParameter = id_categoria.HasValue ?
                new ObjectParameter("id_categoria", id_categoria) :
                new ObjectParameter("id_categoria", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_filtroTwoFour_Result>("sp_filtroTwoFour", r_socialParameter, sectorParameter, paisParameter, id_categoriaParameter);
        }
    
        public virtual ObjectResult<sp_filtroTwoThree_Result> sp_filtroTwoThree(string r_social, string sector, Nullable<bool> id_categoria)
        {
            var r_socialParameter = r_social != null ?
                new ObjectParameter("r_social", r_social) :
                new ObjectParameter("r_social", typeof(string));
    
            var sectorParameter = sector != null ?
                new ObjectParameter("sector", sector) :
                new ObjectParameter("sector", typeof(string));
    
            var id_categoriaParameter = id_categoria.HasValue ?
                new ObjectParameter("id_categoria", id_categoria) :
                new ObjectParameter("id_categoria", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_filtroTwoThree_Result>("sp_filtroTwoThree", r_socialParameter, sectorParameter, id_categoriaParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagramdefinition_Result> sp_helpdiagramdefinition(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagramdefinition_Result>("sp_helpdiagramdefinition", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagrams_Result> sp_helpdiagrams(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagrams_Result>("sp_helpdiagrams", diagramnameParameter, owner_idParameter);
        }
    
        public virtual int sp_renamediagram(string diagramname, Nullable<int> owner_id, string new_diagramname)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var new_diagramnameParameter = new_diagramname != null ?
                new ObjectParameter("new_diagramname", new_diagramname) :
                new ObjectParameter("new_diagramname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_renamediagram", diagramnameParameter, owner_idParameter, new_diagramnameParameter);
        }
    
        public virtual int sp_upgraddiagrams()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_upgraddiagrams");
        }
    
        public virtual int sp_insertSector(string nombre)
        {
            var nombreParameter = nombre != null ?
                new ObjectParameter("nombre", nombre) :
                new ObjectParameter("nombre", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_insertSector", nombreParameter);
        }
    
        public virtual int sp_updateSector(Nullable<int> id, string nombre)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("nombre", nombre) :
                new ObjectParameter("nombre", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_updateSector", idParameter, nombreParameter);
        }
    
        public virtual ObjectResult<sp_buscarLugares_Result> sp_buscarLugares()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_buscarLugares_Result>("sp_buscarLugares");
        }
    
        public virtual int sp_insertCiudad(Nullable<byte> id, string nCiudad)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(byte));
    
            var nCiudadParameter = nCiudad != null ?
                new ObjectParameter("NCiudad", nCiudad) :
                new ObjectParameter("NCiudad", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_insertCiudad", idParameter, nCiudadParameter);
        }
    
        public virtual int sp_insertPais(string npais)
        {
            var npaisParameter = npais != null ?
                new ObjectParameter("Npais", npais) :
                new ObjectParameter("Npais", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_insertPais", npaisParameter);
        }
    
        public virtual int sp_updateCiudad(Nullable<byte> id, string nCiudad)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(byte));
    
            var nCiudadParameter = nCiudad != null ?
                new ObjectParameter("NCiudad", nCiudad) :
                new ObjectParameter("NCiudad", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_updateCiudad", idParameter, nCiudadParameter);
        }
    
        public virtual int sp_updatePais(Nullable<byte> id, string npais)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(byte));
    
            var npaisParameter = npais != null ?
                new ObjectParameter("Npais", npais) :
                new ObjectParameter("Npais", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_updatePais", idParameter, npaisParameter);
        }
    
        public virtual int sp_insertContacto(string nombre, string razón_Social, string nIT, string telefono, string direccion, string correo, string descripcion, Nullable<byte> id_sector, Nullable<byte> id_ubicacion, Nullable<bool> id_categoria, Nullable<bool> id_estado)
        {
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            var razón_SocialParameter = razón_Social != null ?
                new ObjectParameter("Razón_Social", razón_Social) :
                new ObjectParameter("Razón_Social", typeof(string));
    
            var nITParameter = nIT != null ?
                new ObjectParameter("NIT", nIT) :
                new ObjectParameter("NIT", typeof(string));
    
            var telefonoParameter = telefono != null ?
                new ObjectParameter("Telefono", telefono) :
                new ObjectParameter("Telefono", typeof(string));
    
            var direccionParameter = direccion != null ?
                new ObjectParameter("Direccion", direccion) :
                new ObjectParameter("Direccion", typeof(string));
    
            var correoParameter = correo != null ?
                new ObjectParameter("Correo", correo) :
                new ObjectParameter("Correo", typeof(string));
    
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("Descripcion", descripcion) :
                new ObjectParameter("Descripcion", typeof(string));
    
            var id_sectorParameter = id_sector.HasValue ?
                new ObjectParameter("id_sector", id_sector) :
                new ObjectParameter("id_sector", typeof(byte));
    
            var id_ubicacionParameter = id_ubicacion.HasValue ?
                new ObjectParameter("id_ubicacion", id_ubicacion) :
                new ObjectParameter("id_ubicacion", typeof(byte));
    
            var id_categoriaParameter = id_categoria.HasValue ?
                new ObjectParameter("id_categoria", id_categoria) :
                new ObjectParameter("id_categoria", typeof(bool));
    
            var id_estadoParameter = id_estado.HasValue ?
                new ObjectParameter("id_estado", id_estado) :
                new ObjectParameter("id_estado", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_insertContacto", nombreParameter, razón_SocialParameter, nITParameter, telefonoParameter, direccionParameter, correoParameter, descripcionParameter, id_sectorParameter, id_ubicacionParameter, id_categoriaParameter, id_estadoParameter);
        }
    
        public virtual int sp_updateContacto(Nullable<int> id, string nombre, string razón_Social, string nIT, string telefono, string direccion, string correo, string descripcion, Nullable<byte> id_sector, Nullable<byte> id_ubicacion, Nullable<bool> id_categoria, Nullable<bool> id_estado)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            var razón_SocialParameter = razón_Social != null ?
                new ObjectParameter("Razón_Social", razón_Social) :
                new ObjectParameter("Razón_Social", typeof(string));
    
            var nITParameter = nIT != null ?
                new ObjectParameter("NIT", nIT) :
                new ObjectParameter("NIT", typeof(string));
    
            var telefonoParameter = telefono != null ?
                new ObjectParameter("Telefono", telefono) :
                new ObjectParameter("Telefono", typeof(string));
    
            var direccionParameter = direccion != null ?
                new ObjectParameter("Direccion", direccion) :
                new ObjectParameter("Direccion", typeof(string));
    
            var correoParameter = correo != null ?
                new ObjectParameter("Correo", correo) :
                new ObjectParameter("Correo", typeof(string));
    
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("Descripcion", descripcion) :
                new ObjectParameter("Descripcion", typeof(string));
    
            var id_sectorParameter = id_sector.HasValue ?
                new ObjectParameter("id_sector", id_sector) :
                new ObjectParameter("id_sector", typeof(byte));
    
            var id_ubicacionParameter = id_ubicacion.HasValue ?
                new ObjectParameter("id_ubicacion", id_ubicacion) :
                new ObjectParameter("id_ubicacion", typeof(byte));
    
            var id_categoriaParameter = id_categoria.HasValue ?
                new ObjectParameter("id_categoria", id_categoria) :
                new ObjectParameter("id_categoria", typeof(bool));
    
            var id_estadoParameter = id_estado.HasValue ?
                new ObjectParameter("id_estado", id_estado) :
                new ObjectParameter("id_estado", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_updateContacto", idParameter, nombreParameter, razón_SocialParameter, nITParameter, telefonoParameter, direccionParameter, correoParameter, descripcionParameter, id_sectorParameter, id_ubicacionParameter, id_categoriaParameter, id_estadoParameter);
        }
    
        public virtual ObjectResult<sp_consultaTodo_Result5> sp_consultaTodo(Nullable<bool> id_categoria)
        {
            var id_categoriaParameter = id_categoria.HasValue ?
                new ObjectParameter("id_categoria", id_categoria) :
                new ObjectParameter("id_categoria", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_consultaTodo_Result5>("sp_consultaTodo", id_categoriaParameter);
        }
    
        public virtual int sp_deleteDocu(Nullable<short> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(short));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_deleteDocu", idParameter);
        }
    
        public virtual int sp_insertDocu(string nombre, string ruta, string observa, Nullable<int> id_contacto)
        {
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            var rutaParameter = ruta != null ?
                new ObjectParameter("Ruta", ruta) :
                new ObjectParameter("Ruta", typeof(string));
    
            var observaParameter = observa != null ?
                new ObjectParameter("observa", observa) :
                new ObjectParameter("observa", typeof(string));
    
            var id_contactoParameter = id_contacto.HasValue ?
                new ObjectParameter("id_contacto", id_contacto) :
                new ObjectParameter("id_contacto", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_insertDocu", nombreParameter, rutaParameter, observaParameter, id_contactoParameter);
        }
    
        public virtual ObjectResult<sp_filtroOne_Result1> sp_filtroOne(string nombre, Nullable<bool> id_categoria)
        {
            var nombreParameter = nombre != null ?
                new ObjectParameter("nombre", nombre) :
                new ObjectParameter("nombre", typeof(string));
    
            var id_categoriaParameter = id_categoria.HasValue ?
                new ObjectParameter("id_categoria", id_categoria) :
                new ObjectParameter("id_categoria", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_filtroOne_Result1>("sp_filtroOne", nombreParameter, id_categoriaParameter);
        }
    
        public virtual int sp_insertUser(string nombre, string cC, string pass, Nullable<bool> rol, Nullable<bool> estado)
        {
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            var cCParameter = cC != null ?
                new ObjectParameter("CC", cC) :
                new ObjectParameter("CC", typeof(string));
    
            var passParameter = pass != null ?
                new ObjectParameter("pass", pass) :
                new ObjectParameter("pass", typeof(string));
    
            var rolParameter = rol.HasValue ?
                new ObjectParameter("Rol", rol) :
                new ObjectParameter("Rol", typeof(bool));
    
            var estadoParameter = estado.HasValue ?
                new ObjectParameter("Estado", estado) :
                new ObjectParameter("Estado", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_insertUser", nombreParameter, cCParameter, passParameter, rolParameter, estadoParameter);
        }
    
        public virtual int sp_updateUser(Nullable<byte> id, string nombre, string cC, string pass, Nullable<bool> rol, Nullable<bool> estado)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(byte));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            var cCParameter = cC != null ?
                new ObjectParameter("CC", cC) :
                new ObjectParameter("CC", typeof(string));
    
            var passParameter = pass != null ?
                new ObjectParameter("pass", pass) :
                new ObjectParameter("pass", typeof(string));
    
            var rolParameter = rol.HasValue ?
                new ObjectParameter("Rol", rol) :
                new ObjectParameter("Rol", typeof(bool));
    
            var estadoParameter = estado.HasValue ?
                new ObjectParameter("Estado", estado) :
                new ObjectParameter("Estado", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_updateUser", idParameter, nombreParameter, cCParameter, passParameter, rolParameter, estadoParameter);
        }
    }
}
