//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DSI.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Progreso
    {
        public int id { get; set; }
        public string Descripcion { get; set; }
        public Nullable<byte> N_Etapa { get; set; }
        public Nullable<bool> Estado { get; set; }
        public Nullable<short> id_Doc { get; set; }
    
        public virtual Documentos Documentos { get; set; }
    }
}
