//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DSI.Datos
{
    using System;
    
    public partial class sp_filtroOneFour_Result1
    {
        public int id { get; set; }
        public string Nombre { get; set; }
        public string Razón_Social { get; set; }
        public string NIT { get; set; }
        public string Sector { get; set; }
        public string Correo { get; set; }
        public string Teléfono { get; set; }
        public string Ciudad { get; set; }
        public string País { get; set; }
        public string Direccion { get; set; }
        public string Descripcion { get; set; }
        public byte id_city { get; set; }
        public Nullable<byte> id_pais { get; set; }
        public Nullable<byte> id_sector { get; set; }
    }
}
