//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DSI.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuarios
    {
        public byte id { get; set; }
        public string Nombre { get; set; }
        public string CC { get; set; }
        public string pass { get; set; }
        public bool id_Rol { get; set; }
        public Nullable<bool> id_Estado { get; set; }
        public string Email { get; set; }
    }
}
